name: Lint

on:
  push:
    paths-ignore: [ "docs/*", "*.md", ".readthedocs.yml", ".github/dependabot.yml", ".vscode" ]
  pull_request:
    paths-ignore: [ "docs/*", "*.md", ".readthedocs.yml", ".github/dependabot.yml", ".vscode" ]
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          dev-requirements.txt
          setup.py
      
    - name: Install dev dependencies
      run: python -m pip install -r dev-requirements.txt
    - name: Install self (dpytest)
      run: python -m pip install .

    - name: Lint
      run: python -m flake8 discord/ext/test tests/ tasks.py